// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ncmrsccaleuhlthxkpxq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5jbXJzY2NhbGV1aGx0aHhrcHhxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDA5NDIwMjgsImV4cCI6MjA1NjUxODAyOH0.SYuExcQ_bDlFz5C3S-9gnh9PdSlBPZTw1GnH0pwEHuc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);